/**
 * https://github.com/kangax/html-minifier#options-quick-reference
 */

module.exports = {

    prod: {
        options: {
            caseSensitive: true,
            collapseBooleanAttributes: false,
            collapseInlineTagWhitespace: false,
            collapseWhitespace: true,
            conservativeCollapse: false,
            customAttrCollapse: false,
            decodeEntities: true,
            html5: true,
            ignoreCustomFragments: [
                (/<p(.*?)>(.*?)<\/p>/g),
                (/<span(.*?)<\/span>/g),
                (/<h1(.*?)<\/h1>/g),
                (/<h2(.*?)<\/h2>/g),
                (/<h3(.*?)<\/h3>/g),
                (/<h4(.*?)<\/h4>/g),
                (/<h5(.*?)<\/h5>/g),
                (/<h6(.*?)<\/h6>/g),
                (/<meta(.*?)>/g),
                (/<link(.*?)>/g),
                (/<html(.*?)>/g),
                (/<script(.*?)<\/script>/g),
            ],
            includeAutoGeneratedTags: false,
            keepClosingSlash: false,
            maxLineLength: 0,
            minifyCSS: true,
            minifyJS: true,
            preserveLineBreaks: false,
            preventAttributesEscaping: false,
            processConditionalComments: true,
            processScripts: [
                "text/html"
            ],
            removeAttributeQuotes: false,
            removeComments: true,
            removeEmptyAttributes: true,
            removeEmptyElements: true,
            removeOptionalTags: true,
            removeRedundantAttributes: false,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            removeTagWhitespace: false,
            sortAttributes: false,
            sortClassName: false,
            trimCustomFragments: true,
            useShortDoctype: false
        },
        files: [{
            expand: true,
            cwd: 'public/prod/',
            src: ['*.html'],
            dest: 'public/prod/',
            ext: '.html'
        }]
    }

};